version: '3'

services:
  postgres-dev:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2023!"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "ludus"
    ports:
      - "15432:5432"
    volumes:
      - /home/freitas/personal/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "freitas@dev.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2023!"
    ports:
      - "16543:80"
    depends_on:
      - postgres-dev
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge